version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - ./:/app
    command: uvicorn app:app --host 0.0.0.0 --port 8000
    restart: unless-stopped

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "8501:8501"
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - ./:/app
    depends_on:
      - backend
    command: streamlit run web_app.py --server.port=8501 --server.address=0.0.0.0
    restart: unless-stopped